# Le decimos a Java que guarde la base de datos en una carpeta llamada "datos_clinica"
spring.datasource.url=jdbc:h2:file:./datos_clinica/endoscopia_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=ludmi2006

# Le decimos que actualice la base de datos si agregamos cosas nuevas, PERO QUE NUNCA BORRE LOS DATOS VIEJOS
spring.jpa.hibernate.ddl-auto=update